# Generated by Django 3.2.8 on 2021-12-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugid', models.IntegerField()),
                ('drugname', models.CharField(max_length=100)),
                ('isopioid', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'pd_drugs',
            },
        ),
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npi', models.CharField(max_length=10)),
                ('Fname', models.CharField(max_length=30)),
                ('Lname', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=7)),
                ('State', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'pd_prescriber',
            },
        ),
    ]
