# Generated by Django 3.2.8 on 2021-12-02 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpioidData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='drugid',
        ),
    ]
