# Generated by Django 3.2.8 on 2021-12-02 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpioidData', '0002_remove_drug_drugid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'pd_credential',
            },
        ),
        migrations.CreateModel(
            name='Specialtie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_title', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'pd_specialtie',
            },
        ),
        migrations.CreateModel(
            name='PrescriberCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npi', models.IntegerField()),
                ('credential_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='OpioidData.credential')),
            ],
            options={
                'db_table': 'prescriber_credential',
            },
        ),
    ]
